version: '3'

services:
  surgio:
    image: quericy/surgio-docker:latest
    build: .
    restart: unless-stopped
    container_name: surgio
    ports:
        - "23000:3000"
    volumes:
        - ./config:/var/config
    environment:
      - AUTOGEN_INTERVAL="1h" # format: xh | xm | xhxm
